{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "Resilient SOAR",
                    "vendor": "IBM",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "38"
                        }
                    ]
                }
            ],
            "datePublic": "2020-08-27T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "IBM Resilient SOAR V38.0 users may experience a denial of service of the SOAR Platform due to a insufficient input validation. IBM X-Force ID: 165589."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "LOW",
                        "baseScore": 4.3,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "exploitCodeMaturity": "UNPROVEN",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "LOW",
                        "remediationLevel": "OFFICIAL_FIX",
                        "reportConfidence": "CONFIRMED",
                        "scope": "UNCHANGED",
                        "temporalScore": 3.8,
                        "temporalSeverity": "LOW",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/I:N/PR:L/AV:N/C:N/S:U/AC:L/A:L/UI:N/RL:O/RC:C/E:U",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "Denial of Service",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2020-08-28T14:35:19",
                "orgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
                "shortName": "ibm"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://www.ibm.com/support/pages/node/6323645"
                },
                {
                    "name": "ibm-resilient-cve20194533-dos (165589)",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_XF"
                    ],
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/165589"
                }
            ]
        }
    },
    "cveMetadata": {
        "assignerOrgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
        "assignerShortName": "ibm",
        "cveId": "CVE-2019-4533",
        "dateReserved": "2019-01-03T00:00:00",
        "dateUpdated": "2020-08-28T14:35:19",
        "state": "PUBLISHED",
        "datePublished": "2020-08-28T14:35:19.141907Z"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
