{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "Business Automation Workflow",
                    "vendor": "IBM",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "18.0.0.0"
                        },
                        {
                            "status": "affected",
                            "version": "18.0.0.1"
                        },
                        {
                            "status": "affected",
                            "version": "18.0.0.2"
                        }
                    ]
                }
            ],
            "datePublic": "2019-04-04T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "IBM Business Automation Workflow and Business Process Manager 18.0.0.0, 18.0.0.1, and 18.0.0.2 are vulnerable to a denial of service attack. An authenticated attacker might send a specially crafted request that exhausts server-side memory. IBM X-Force ID: 154774."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "LOW",
                        "baseScore": 4.3,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "exploitCodeMaturity": "UNPROVEN",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "LOW",
                        "remediationLevel": "OFFICIAL_FIX",
                        "reportConfidence": "CONFIRMED",
                        "scope": "UNCHANGED",
                        "temporalScore": 3.8,
                        "temporalSeverity": "LOW",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/A:L/PR:L/I:N/AC:L/C:N/S:U/UI:N/AV:N/RL:O/E:U/RC:C",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "Denial of Service",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2019-04-08T14:50:37",
                "orgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
                "shortName": "ibm"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://www.ibm.com/support/docview.wss?uid=ibm10794831"
                },
                {
                    "name": "ibm-baw-cve20181997-dos (154774)",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_XF"
                    ],
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/154774"
                }
            ]
        }
    },
    "cveMetadata": {
        "assignerOrgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
        "assignerShortName": "ibm",
        "cveId": "CVE-2018-1997",
        "dateReserved": "2017-12-13T00:00:00",
        "dateUpdated": "2019-04-08T14:50:37",
        "state": "PUBLISHED",
        "datePublished": "2019-04-08T14:50:37.952252Z"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
