{
    "containers": {
        "cna": {
            "affected": [
                {
                    "collection_url": "https://packages.fedoraproject.org/",
                    "defaultStatus": "affected",
                    "packageName": "python3",
                    "product": "Fedora",
                    "vendor": "Fedora",
                    "x_redhatStatus": "Affected"
                }
            ],
            "datePublic": "2012-04-14T00:00:00Z",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "CVE-2012-2135 python3: Data leaks, memory damage and possible crash in utf-16 decoder"
                }
            ],
            "metrics": [
                {
                    "other": {
                        "content": {
                            "namespace": "https://access.redhat.com/security/updates/classification/",
                            "value": "Low"
                        },
                        "type": "Red Hat severity rating"
                    }
                },
                {
                    "cvssV2_0": {
                        "accessComplexity": "LOW",
                        "accessVector": "NETWORK",
                        "authentication": "NONE",
                        "availabilityImpact": "PARTIAL",
                        "availabilityRequirement": "NOT_DEFINED",
                        "baseScore": 5,
                        "collateralDamagePotential": "NOT_DEFINED",
                        "confidentialityImpact": "NONE",
                        "confidentialityRequirement": "NOT_DEFINED",
                        "environmentalScore": 0,
                        "exploitability": "NOT_DEFINED",
                        "integrityImpact": "NONE",
                        "integrityRequirement": "NOT_DEFINED",
                        "remediationLevel": "NOT_DEFINED",
                        "reportConfidence": "NOT_DEFINED",
                        "targetDistribution": "NOT_DEFINED",
                        "temporalScore": 0,
                        "vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
                        "version": "2.0"
                    },
                    "format": "CVSS"
                }
            ],
            "providerMetadata": {
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat",
                "dateUpdated": "2023-02-02T14:42:28.582Z"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "http://bugs.python.org/issue14579"
                },
                {
                    "name": "51087",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/51087"
                },
                {
                    "name": "51089",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/51089"
                },
                {
                    "name": "[oss-security] 20120425 CVE Request: Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler aligned_end is not updated",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2012/04/25/2"
                },
                {
                    "name": "[oss-security] 20120425 Re: CVE Request: Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler aligned_end is not updated",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2012/04/25/4"
                },
                {
                    "name": "USN-1615-1",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_UBUNTU"
                    ],
                    "url": "http://www.ubuntu.com/usn/USN-1615-1"
                },
                {
                    "name": "USN-1616-1",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_UBUNTU"
                    ],
                    "url": "http://www.ubuntu.com/usn/USN-1616-1"
                },
                {
                    "tags": [
                        "vdb-entry",
                        "x_redhatRef"
                    ],
                    "url": "https://access.redhat.com/security/cve/CVE-2012-2135"
                },
                {
                    "name": "RHBZ#816153",
                    "tags": [
                        "issue-tracking",
                        "x_redhatRef"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=816153"
                }
            ],
            "timeline": [
                {
                    "lang": "en",
                    "time": "2012-04-20T00:00:00Z",
                    "value": "Reported to Red Hat."
                },
                {
                    "lang": "en",
                    "time": "2012-04-14T00:00:00Z",
                    "value": "Made public."
                }
            ],
            "title": "CVE-2012-2135 python3: Data leaks, memory damage and possible crash in utf-16 decoder"
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2012-2135",
        "datePublished": "2012-08-14T22:00:00",
        "dateReserved": "2012-04-04T00:00:00",
        "dateUpdated": "2023-02-02T14:42:28.582Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
