{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "MongoDB Server",
                    "vendor": "MongoDB Inc.",
                    "versions": [
                        {
                            "lessThan": "4.4.1",
                            "status": "affected",
                            "version": "4.4",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "datePublic": "2020-11-30T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A user authorized to perform database queries may cause denial of service by issuing a specially crafted query which violates an invariant in the server selection subsystem. This issue affects: MongoDB Server version 4.4 prior to 4.4.1. Versions before 4.4 are not affected."
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 6.5,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                        "version": "3.1"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-755",
                            "description": "CWE-755 Improper Handling of Exceptional Conditions",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2020-11-23T15:05:15",
                "orgId": "a39b4221-9bd0-4244-95fc-f3e2e07f1deb",
                "shortName": "mongodb"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://jira.mongodb.org/browse/SERVER-50170"
                }
            ],
            "source": {
                "discovery": "INTERNAL"
            },
            "title": "Specific query can cause a DoS against MongoDB Server",
            "x_generator": {
                "engine": "Vulnogram 0.0.9"
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "a39b4221-9bd0-4244-95fc-f3e2e07f1deb",
        "assignerShortName": "mongodb",
        "cveId": "CVE-2020-7926",
        "dateReserved": "2020-01-23T00:00:00",
        "dateUpdated": "2020-11-23T15:05:15",
        "state": "PUBLISHED",
        "datePublished": "2020-11-23T15:05:15.299714Z"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
