{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "cveMetadata": {
        "state": "PUBLISHED",
        "cveId": "CVE-2022-46285",
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "dateUpdated": "2023-02-07T00:00:00",
        "dateReserved": "2023-01-09T00:00:00",
        "datePublished": "2023-02-07T00:00:00"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat",
                "dateUpdated": "2023-02-07T00:00:00"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A flaw was found in libXpm. This issue occurs when parsing a file with a comment not closed; the end-of-file condition will not be detected, leading to an infinite loop and resulting in a Denial of Service in the application linked to the library."
                }
            ],
            "affected": [
                {
                    "vendor": "n/a",
                    "product": "libXpm",
                    "versions": [
                        {
                            "version": "3.5.15",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "references": [
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2160092"
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "CWE",
                            "lang": "en",
                            "description": "CWE-835",
                            "cweId": "CWE-835"
                        }
                    ]
                }
            ]
        }
    }
}
