{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "opcua",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "lessThan": "unspecified",
                            "status": "affected",
                            "version": "0",
                            "versionType": "custom"
                        }
                    ]
                },
                {
                    "product": "asyncua",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "lessThan": "unspecified",
                            "status": "affected",
                            "version": "0",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "value": "Vera Mens"
                },
                {
                    "lang": "en",
                    "value": "Uri Katz"
                },
                {
                    "lang": "en",
                    "value": "Sharon Brizinov of Team82 (Claroty Research)"
                }
            ],
            "datePublic": "2022-08-23T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "All versions of package opcua; all versions of package asyncua are vulnerable to Denial of Service (DoS) due to a missing limitation on the number of received chunks - per single session or in total for all concurrent sessions. An attacker can exploit this vulnerability by sending an unlimited number of huge chunks (e.g. 2GB each) without sending the Final closing chunk."
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 7.5,
                        "baseSeverity": "HIGH",
                        "confidentialityImpact": "NONE",
                        "exploitCodeMaturity": "PROOF_OF_CONCEPT",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "NONE",
                        "remediationLevel": "NOT_DEFINED",
                        "reportConfidence": "NOT_DEFINED",
                        "scope": "UNCHANGED",
                        "temporalScore": 7.1,
                        "temporalSeverity": "HIGH",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H/E:P",
                        "version": "3.1"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "Denial of Service (DoS)",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-08-23T05:05:11",
                "orgId": "bae035ff-b466-4ff4-94d0-fc9efd9e1730",
                "shortName": "snyk"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://security.snyk.io/vuln/SNYK-PYTHON-OPCUA-2988730"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-2988731"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/FreeOpcUa/python-opcua/issues/1466"
                }
            ],
            "title": "Denial of Service (DoS)"
        }
    },
    "cveMetadata": {
        "assignerOrgId": "bae035ff-b466-4ff4-94d0-fc9efd9e1730",
        "assignerShortName": "snyk",
        "cveId": "CVE-2022-25304",
        "dateReserved": "2022-02-24T00:00:00",
        "dateUpdated": "2022-08-23T05:05:11",
        "state": "PUBLISHED",
        "datePublished": "2022-08-23T05:05:11.904697Z"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
